name: Release

on:
  push:
    tags:
    - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release -l trx
    - name: Nuget Pack
      run: dotnet pack .\src\Microsoft.Diagnostics.EventFlow.Outputs.Loki\Microsoft.Diagnostics.EventFlow.Outputs.Loki.csproj -c Release --no-build -o .\artifacts